name: CI

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: swift:5.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build & Test
        run: swift test -c release --enable-test-discovery
